apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    app: Title
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"
