services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./components/mysql/:/docker-entrypoint-initdb.d/
      - ./components/mysql/data:/data
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine3.18
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/conf/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
